on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
      - name: Clone GuillaumeFalourd/formulas-training PRIVATE repository
        uses: GuillaumeFalourd/clone-github-repo-action@v2
        with:
          owner: 'margaritadanshina'
          repository: 'test-repo-for-action'
          access-token: ${{ secrets.test }}
      
      - name: Access cloned repository content
        run: |
          echo "ROOT"
          ls -la
          echo "CLONED REPO"
          cd formulas-training
          ls -la

