on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout tools repo
      - run: |
          curl -i -u margaritadanshina:${{ secrets.THE_TOKEN}} -X POST  -H "Accept: application/vnd.github.v3+json" https://github.com/api/v3/repos/margaritadanshina/repos -d '{"name": "new_repo"}'

      
      
